/**
 * keystone.config.json loader
 *
 * Reads project-level config so developers don't need to repeat flags.
 * Generated by `keystone init` and `keystone config`.
 */

import * as fs from "node:fs";
import * as path from "node:path";

export interface KeystoneConfig {
    name?: string;
    description?: string;
    wallet?: string;
    privateKey?: string;
    cluster?: "devnet" | "mainnet-beta";
    category?: string;
    provider?: string;
    model?: string;
    apiKey?: string;
    apiUrl?: string;
}

const CONFIG_FILE = "keystone.config.json";

/**
 * Load keystone.config.json from the target directory or cwd.
 * Returns defaults for any missing fields.
 */
export function loadConfig(dir?: string): KeystoneConfig {
    const searchDir = dir ? path.resolve(dir) : process.cwd();
    const configPath = path.join(searchDir, CONFIG_FILE);

    if (!fs.existsSync(configPath)) {
        return {};
    }

    try {
        const raw = fs.readFileSync(configPath, "utf-8");
        return JSON.parse(raw) as KeystoneConfig;
    } catch (e) {
        console.warn(`[config] Failed to parse ${CONFIG_FILE}:`, (e as Error).message);
        return {};
    }
}

/**
 * Save config to keystone.config.json in the target directory.
 */
export function saveConfig(config: KeystoneConfig, dir?: string): void {
    const searchDir = dir ? path.resolve(dir) : process.cwd();
    const configPath = path.join(searchDir, CONFIG_FILE);
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");
}

/**
 * Merge CLI flags over config file values.
 * CLI flags take precedence over config values.
 */
export function mergeConfig(config: KeystoneConfig, flags: Partial<KeystoneConfig>): KeystoneConfig {
    const merged: KeystoneConfig = { ...config };
    for (const [key, value] of Object.entries(flags)) {
        if (value !== undefined && value !== null && value !== "") {
            (merged as any)[key] = value;
        }
    }
    return merged;
}
