[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Optimize build for production
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  # Increase timeout for scraping functions
  timeout = 15

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle static files for Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize API routes caching
[[headers]]
  for = "/api/airdrops/speculative/solana"
  [headers.values]
    Cache-Control = "private, max-age=60"