/**
 * POST /api/studio/export-pdf — Generate PDF from mini-app output.
 *
 * Uses Cloudflare Browser Rendering to render HTML/URL and produce a PDF.
 * For treasury reports, tax summaries, impact reports, audit trails.
 */

import { NextRequest, NextResponse } from "next/server";
import { pdf } from "@/lib/cloudflare/cf-browser";

const KEYSTONE_FOOTER = `
<div style="font-size:8px; color:#666; width:100%; text-align:center; padding:5px 0;">
  <span>Generated by dreyv OS</span>
  <span style="margin:0 10px;">|</span>
  <span class="date"></span>
  <span style="margin:0 10px;">|</span>
  <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
</div>`;

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const {
            html,
            url,
            title = "dreyv Report",
            landscape = false,
            format = "A4",
            includeHeader = false,
            includeFooter = true,
        } = body;

        if (!html && !url) {
            return NextResponse.json({ error: "Provide html or url" }, { status: 400 });
        }

        const headerTemplate = includeHeader
            ? `<div style="font-size:10px; color:#666; width:100%; text-align:center; padding:5px 0; font-weight:bold;">${title}</div>`
            : "";

        const pdfBuffer = await pdf({
            html,
            url,
            pdfOptions: {
                format: format as any,
                landscape,
                printBackground: true,
                displayHeaderFooter: includeHeader || includeFooter,
                headerTemplate,
                footerTemplate: includeFooter ? KEYSTONE_FOOTER : "",
                margin: {
                    top: includeHeader ? "40px" : "20px",
                    bottom: includeFooter ? "40px" : "20px",
                    left: "20px",
                    right: "20px",
                },
            },
            // Inject print-friendly styles
            addStyleTag: html
                ? [{
                    content: `
              body { margin: 0; background: white; color: #111; font-family: system-ui, sans-serif; }
              @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
            `,
                }]
                : undefined,
        });

        // Return as downloadable PDF
        return new NextResponse(pdfBuffer, {
            status: 200,
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="${title.replace(/[^a-zA-Z0-9-_ ]/g, "")}.pdf"`,
                "Content-Length": String(pdfBuffer.byteLength),
            },
        });
    } catch (err) {
        console.error("[export-pdf] Error:", err);
        return NextResponse.json(
            { error: err instanceof Error ? err.message : "PDF generation failed" },
            { status: 500 }
        );
    }
}
